---
apiVersion: v1
offerings:
  - name: watsonx_generative_ai
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: 30045dc8-ab5b-4fcd-97e6-28d0655809b2
    variations:
      - name: genai-stack-standard
        mark_ready: false
        install_type: fullstack
        format_kind: stack
        validation_type: projects
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
