---
apiVersion: v1
offerings:
  - name: Watson_X_-_Generative_AI
    kind: solution
    catalog_id: 7df1e4ca-d54c-4fd0-82ce-3d13247308cd
    offering_id: d113359a-921d-4474-965a-4e612c4c1bfe
    variations:
      - name: genai-stack-1234
        mark_ready: false
        install_type: fullstack
        format_kind: stack
        validation_type: projects
        scc:
          instance_id: 1c7d5f78-9262-44c3-b779-b28fe4d88c37
          region: us-south
